import type { Metadata } from "next";
import "@/styles/globals.css";
import HeadSEO from "@/components/HeadSEO";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/Toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <HeadSEO />
      <body className="bg-black">
        <div className="min-h-screen flex flex-col justify-center text-white items-center">
          {/* @ts-expect-error Server Component */}
          <Navbar />
          <div className="mt-10">{children}</div>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
